// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukwarugotqbeoxwfajpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrd2FydWdvdHFiZW94d2ZhanB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODc2NTIsImV4cCI6MjA1NzM2MzY1Mn0.06jQzEopU3Izj_mghtVI1EJ6CunmuQuI2RToCPSIXeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);